services:
  - type: web
    name: irus-ai
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: mixtral-8x7b-32768
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: personal_assistant
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromDotEnv: true
    